title: Alan He
email: alanxh.research@gmail.com
description: >-
  Academic profile and research notes in chemistry and molecular science.
baseurl: ""
url: "https://alan-he-494165.github.io"
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - research.md

markdown: kramdown
highlighter: rouge

# Build settings
permalink: /:categories/:year/:month/:day/:title/
